name: Deploy to EC2

on:
  push:
    branches:
      - githubactions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'movecloud-development/nodejs-application'


      - name: Install dependencies
        run: npm ci

      # - name: Build application
      #   run: npm run build
      - name: check path and list the files
        run: pwd && ls

      - name: Copy JAR to EC2 Instance (via SSH)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Replace with your EC2 instance public IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # Replace with your EC2 instance username
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Replace with your EC2 instance SSH private key (base64-encoded)
          # source: "target/*.jar"
          source: "*"
          # source: "/home/runner/work/spring-petclinic/spring-petclinic/file1.txt"
          target: "/tmp"  # Replace with the target path on the EC2 instance
          # target: "/home"
          debug: "true"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /tmp
            sudo yum update
            sudo yum install -y nodejs
            ps aux  |  grep -i "/usr/bin/node src/index.js"  |  awk '{print $2}'  |  xargs sudo kill -9
            sudo npm start &

